<a href="https://colab.research.google.com/github/H1ghSpeed/g_colab/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_pytorch_%D0%A3%D1%80%D0%BE%D0%BA1_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [ ]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones([3, 4, 2])

In [ ]:
torch.Tensor([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [3]:
x = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [ ]:
x.size()

torch.Size([3, 4])

In [ ]:
x.shape

torch.Size([3, 4])

In [ ]:
x[0]            #нулевой массив

tensor([1., 2., 3., 4.])

In [ ]:
x[0][0]         #нулевой массив, нулевой элемент

tensor(1.)

In [ ]:
x[:, 0]         #Слайс по левому верхнему числу в тензоре

tensor([1., 5., 9.])

In [ ]:
x + 10          #Поэлементное прибавление ко всем элементам

In [ ]:
x ** 2          #Поэлементное возведение в квадрат

In [4]:
y = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [ ]:
x+y             #Важно, что бы был один размер. Поэлементное суммирование

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [ ]:
x*y             #По аналогии выше

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])

In [5]:
torch.exp(x)            #Взятие экспоненты

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03],
        [8.1031e+03, 2.2026e+04, 5.9874e+04, 1.6275e+05]])

In [6]:
torch.log(x)          #Логарифмирование

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794],
        [2.1972, 2.3026, 2.3979, 2.4849]])

In [7]:
torch.sin(x)          #Взятие синуса

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568],
        [-0.9589, -0.2794,  0.6570,  0.9894],
        [ 0.4121, -0.5440, -1.0000, -0.5366]])

In [8]:
x > 3                 #Логическая операция, выполняется поэлементно и возвращает булевой тензор

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [9]:
mask = x > 3        #Составление маски

In [10]:
x[mask]             #Передаем  индексы в элемент x

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
x[x>3]              #Эквивалентно операции выше

In [ ]:
#Копирование

In [ ]:
y = x               #Ссылка на объект x, копирования не происходит

In [ ]:
y = x.clone()       #Происходит клонирование(копирование)

In [11]:
x.dtype             #Тип данных. Аттрибут data type

torch.float32

In [15]:
x = x.double()
print(x)
x = x.int()
print(x)
x = x.float()
print(x)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], dtype=torch.float64)
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]], dtype=torch.int32)
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [3]:
import numpy as np

In [18]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8]])


In [20]:
x = torch.from_numpy(x)         #Преобразование из np.ndarray в torch.Tensor

In [21]:
x = x.numpy()                   #Преобразование из torch.Tensor в np.ndarray

In [9]:
x = torch.rand([2000, 3000])

In [4]:
torch.cuda.is_available()         #Определение, есть ли у нас куда на компьютере

True

In [5]:
torch.device('cuda:0')            #Девайс который отвечает за видеокарту. Индекс выбирает конкретную видеокарту

device(type='cuda', index=0)

In [6]:
torch.device('cpu')               #Перевод девайса на cpu

device(type='cpu')

In [7]:
device = torch.device('cuda:0') if torch.cuda.is_available() else torch.device('cpu')

In [10]:
x_cuda = x.to(device)

In [13]:
%time y = (x - x + x * 10.0 ) ** 2

CPU times: user 16.9 ms, sys: 40.9 ms, total: 57.8 ms
Wall time: 59.4 ms


In [16]:
%time y_cuda = (x_cuda - x_cuda + x_cuda * 10.0 ) ** 2

CPU times: user 222 µs, sys: 916 µs, total: 1.14 ms
Wall time: 1.16 ms
