<a href="https://colab.research.google.com/github/H1ghSpeed/g_colab/blob/main/%D0%9E%D0%B1%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_pytorch_%D0%A3%D1%80%D0%BE%D0%BA1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
torch.ones([3, 4, 2])

In [ ]:
torch.Tensor([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])

In [5]:
x = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [6]:
x.size()

torch.Size([3, 4])

In [7]:
x.shape

torch.Size([3, 4])

In [8]:
x[0]            #нулевой массив

tensor([1., 2., 3., 4.])

In [9]:
x[0][0]         #нулевой массив, нулевой элемент

tensor(1.)

In [10]:
x[:, 0]         #Слайс по левому верхнему числу в тензоре

tensor([1., 5., 9.])

In [ ]:
x + 10          #Поэлементное прибавление ко всем элементам

In [ ]:
x ** 2          #Поэлементное возведение в квадрат

In [13]:
y = torch.Tensor([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])

In [14]:
x+y             #Важно, что бы был один размер. Поэлементное суммирование

tensor([[ 2.,  4.,  6.,  8.],
        [10., 12., 14., 16.],
        [18., 20., 22., 24.]])

In [15]:
x*y             #По аналогии выше

tensor([[  1.,   4.,   9.,  16.],
        [ 25.,  36.,  49.,  64.],
        [ 81., 100., 121., 144.]])